(() => {
'use strict';
const C=window.XGRRCore,$=id=>document.getElementById(id);
const A=()=>window.XGRRApp;
let lastResult=null;
const fmt=(v,d=3)=>Number.isFinite(+v)?(+v).toFixed(d):'—';
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const nap=(n=0)=>new Promise(r=>setTimeout(r,n));
function resetOutput(){lastResult=null;['optBestValue','optBestGRR','optBestParts','optBestNdc'].forEach(id=>{if($(id))$(id).textContent='—'});if($('optimizerOutput'))$('optimizerOutput').innerHTML=''}
function selectedRuleIndex(){return Math.max(0,Math.floor(+$('optRule').value||0))}
function makePrepared(){
 const app=A(),S=app?.getState(),rules=app?.getCurrentRules()||[],measurementMetric=app?.getMeasurementMetric();
 if(!app||!S?.samples?.length||!rules.length||!measurementMetric)throw new Error('Import data and configure measurement/filter rules first.');
 const idx=selectedRuleIndex();if(idx>=rules.length)throw new Error('Selected optimizer rule no longer exists.');
 const byPart=new Map();
 for(const s of S.samples){const p=app.getPartId(s);let d=byPart.get(p);if(!d){d={part:p,samples:[],rows:[]};byPart.set(p,d)}const values=rules.map(r=>s.metrics[r.metric]);d.samples.push(values);const mv=s.metrics[measurementMetric];if(Number.isFinite(mv)){const f=S.files.find(x=>x.id===s.fileId),mach=f?.machine||'Unknown';d.rows.push({part:p,machine:mach,value:mv})}}
 return {app,S,rules,measurementMetric,ruleIndex:idx,byPart};
}
function partHits(d,rules,idx,direction,t){for(const values of d.samples){const hits=rules.map((r,i)=>i===idx?C.compare(values[i],direction,t,r.b):C.compare(values[i],r.op,r.a,r.b));const join=$('ruleJoin')?.value||'ALL';if(join==='ALL'?hits.every(Boolean):hits.some(Boolean))return true}return false}
async function scan(prep,from,to,step,direction,preferredParts){
 const lo=Math.min(from,to),hi=Math.max(from,to),thresholds=[];for(let t=lo;t<=hi+step*1e-8;t+=step)thresholds.push(+t.toFixed(10));if(thresholds.length>500)throw new Error('Too many thresholds. Increase Step so the scan has 500 points or fewer.');
 const results=[],allParts=[...prep.byPart.values()];
 for(let i=0;i<thresholds.length;i++){
  const t=thresholds[i],selected=[];for(const d of allParts)if(partHits(d,prep.rules,prep.ruleIndex,direction,t)&&d.rows.length)selected.push(d);
  const rows=selected.flatMap(d=>d.rows),b=prep.app.balanced(rows),base={threshold:t,valid:false,recommended:false,selectedParts:selected.length,commonParts:b.common.length,measurements:rows.length,machines:b.machines.length,repeats:b.min,balancedRows:b.rows.length};
  if(b.machines.length>=2&&b.common.length>=2&&b.min>=2){const g=C.calculateCrossedANOVA(b.rows.map(r=>({part:r.part,machine:r.machine,value:r.value})));if(g.ok&&Number.isFinite(g.pctStudyVariation))Object.assign(base,{valid:true,recommended:preferredParts===0||b.common.length>=preferredParts,pctGRR:g.pctStudyVariation,pctContribution:g.pctContribution,ndc:g.ndc,repeatability:g.variance.repeatability,reproducibility:g.variance.reproducibility,partToPart:g.variance.partToPart})}
  results.push(base);if(i%4===0||i===thresholds.length-1){prep.app.progress('GR&R Optimizer',`Testing threshold ${i+1} / ${thresholds.length}`,50+42*(i+1)/thresholds.length,`${direction} ${fmt(t,4)}`);await nap(0)}
 }
 return results;
}
function render(result){
 lastResult=result;const out=$('optimizerOutput'),valid=result.results.filter(x=>x.valid).sort((a,b)=>a.pctGRR-b.pctGRR);
 if(!valid.length){const maxMachines=Math.max(0,...result.results.map(x=>x.machines||0)),maxCommon=Math.max(0,...result.results.map(x=>x.commonParts||0)),maxRepeats=Math.max(0,...result.results.map(x=>x.repeats||0));const oneMachine=maxMachines<2?'<br><br><b>Only one machine is available.</b> Full GR&R cannot be calculated from one machine; this dataset can only support a repeatability-type study.':'';out.innerHTML=`<div class="opt-warning"><b>No mathematically valid crossed GR&R candidate in this range.</b><br>This is not because GR&R must be below 1%. Crossed GR&R needs at least 2 machines, 2 common parts and 2 repeats per Part × Machine cell.<br><br><b>Best data availability found:</b><br>Machines: ${maxMachines}<br>Common parts: ${maxCommon}<br>Repeats per cell: ${maxRepeats}${oneMachine}</div>`;return}
 const best=valid[0],unit=result.filterMetric?.unit?` ${result.filterMetric.unit}`:'';$('optBestValue').textContent=`${result.direction} ${fmt(best.threshold,4)}${unit}`;$('optBestGRR').textContent=`${fmt(best.pctGRR,2)}%`;$('optBestParts').textContent=best.commonParts.toLocaleString();$('optBestNdc').textContent=best.ndc===Infinity?'∞':best.ndc;
 const coverage=result.preferredParts===0?`No preferred common-pin minimum was requested.`:best.commonParts>=result.preferredParts?`${best.commonParts} common parts meets your preferred minimum of ${result.preferredParts}.`:`The lowest available %GRR uses ${best.commonParts} common parts, below your preferred ${result.preferredParts}. It is shown anyway.`;
 const top=valid.slice(0,25);out.innerHTML=`<div class="opt-note"><b>Lowest available result in the scanned range:</b> ${fmt(best.pctGRR,2)}% at ${result.direction} ${fmt(best.threshold,4)}${unit}. There is no requirement for GR&R to be below 1%.<br><b>Coverage:</b> ${coverage}<br><br><b>Measurement:</b> ${esc(result.measurementMetric.fullLabel)}<br><b>Optimized filter:</b> Rule ${result.ruleIndex+1} · ${esc(result.filterMetric.fullLabel)}</div><div class="opt-table-wrap"><table class="opt-table"><thead><tr><th>Rank</th><th>Threshold</th><th>%GRR</th><th>%Contribution</th><th>Common parts</th><th>Measurements</th><th>Repeats</th><th>ndc</th></tr></thead><tbody>${top.map((r,i)=>`<tr class="${i===0?'best':''}"><td>${i+1}</td><td>${result.direction} ${fmt(r.threshold,4)}${unit}</td><td>${fmt(r.pctGRR,2)}%</td><td>${fmt(r.pctContribution,2)}%</td><td>${r.commonParts}</td><td>${r.measurements}</td><td>${r.repeats}</td><td>${r.ndc===Infinity?'∞':r.ndc}</td></tr>`).join('')}</tbody></table></div><div class="opt-actions"><button id="applyBestThreshold" class="primary">Apply lowest-GR&R threshold & analyze</button><button id="downloadOptCsv" class="ghost">Export optimizer CSV</button></div>`;
 $('applyBestThreshold').onclick=async()=>{if(result.app.applyRuleThreshold(result.ruleIndex,result.direction,best.threshold)){result.app.toast(`Applied Rule ${result.ruleIndex+1}: ${result.direction} ${best.threshold}`);await result.app.analyze()}};$('downloadOptCsv').onclick=()=>downloadCsv(result.results.filter(x=>x.valid),result);
}
function downloadCsv(rows,result){const cols=['Threshold','Direction','GRR_Percent','Contribution_Percent','Common_Parts','Selected_Parts','Measurements','Machines','Repeats','NDC','Filter_Metric','Measurement_Metric'];const lines=[cols.join(',')],q=v=>`"${String(v??'').replaceAll('"','""')}"`;for(const r of [...rows].sort((a,b)=>a.threshold-b.threshold))lines.push([r.threshold,result.direction,r.pctGRR,r.pctContribution,r.commonParts,r.selectedParts,r.measurements,r.machines,r.repeats,r.ndc===Infinity?'Infinity':r.ndc,q(result.filterMetric.fullLabel),q(result.measurementMetric.fullLabel)].join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='GRR_Optimizer_Threshold_Scan.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function optimize(){const app=A();try{resetOutput();const prep=makePrepared(),from=+$('optFrom').value,to=+$('optTo').value,step=+$('optStep').value,preferredParts=Math.max(0,Math.floor(+$('optMinParts').value||0)),direction=$('optDirection').value;if(![from,to,step].every(Number.isFinite)||step<=0)throw new Error('Check optimizer range and step.');const filterKey=prep.rules[prep.ruleIndex].metric,filterMetric=prep.S.metrics.get(filterKey),measurementMetric=prep.S.metrics.get(prep.measurementMetric);app.progress('GR&R Optimizer','Preparing Part / Machine matrix…',8,`${filterMetric?.fullLabel||filterKey} → ${measurementMetric?.fullLabel||prep.measurementMetric}`);await nap(20);const results=await scan(prep,from,to,step,direction,preferredParts);app.progress('GR&R Optimizer','Ranking calculable thresholds from lowest %GRR…',96);await nap(20);const result={...prep,results,from,to,step,direction,preferredParts,filterMetric,measurementMetric};render(result);app.progress('Done','Lowest available GR&R threshold search ready.',100);await nap(100);app.hideProgress()}catch(e){app?.hideProgress();console.error(e);$('optimizerOutput').innerHTML=`<div class="opt-warning"><b>Optimizer stopped.</b><br>${esc(e.message||e)}</div>`;app?.toast(e.message||'Optimizer failed')}}
function sync(){const app=A(),rules=app?.getCurrentRules?.()||[],opt=$('optRule'),btn=$('optimizeBtn');if(!opt||!btn)return;const old=+opt.value;if(!rules.length){opt.innerHTML='<option>No filter rules</option>';opt.disabled=btn.disabled=true;resetOutput();return}const S=app.getState();opt.innerHTML=rules.map((r,i)=>`<option value="${i}">Rule ${i+1}: ${esc(S.metrics.get(r.metric)?.fullLabel||r.metric)}</option>`).join('');opt.value=Number.isInteger(old)&&old<rules.length?String(old):'0';opt.disabled=btn.disabled=false}
$('optimizeBtn').onclick=optimize;$('optRule').onchange=resetOutput;const mo=new MutationObserver(sync);mo.observe($('rules'),{childList:true,subtree:true});$('fileList')&&new MutationObserver(sync).observe($('fileList'),{childList:true,subtree:true});$('resetBtn').addEventListener('click',()=>setTimeout(()=>{sync();resetOutput()},0));sync();
})();