(() => {
'use strict';
const C=window.XGRRCore,$=id=>document.getElementById(id),A=()=>window.XGRRApp;
let lastResult=null;
const fmt=(v,d=3)=>Number.isFinite(+v)?(+v).toFixed(d):'—';
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const nap=(n=0)=>new Promise(r=>setTimeout(r,n));
function resetOutput(){lastResult=null;['optBestValue','optBestGRR','optBestParts','optBestNdc'].forEach(id=>{if($(id))$(id).textContent='—'});if($('optimizerOutput'))$('optimizerOutput').innerHTML=''}
function selectedRuleIndex(){return Math.max(0,Math.floor(+$('optRule').value||0))}
function effectiveMode(){return window.XGRRStudy?.effectiveMode?.()||(([...new Set((A()?.getState?.()?.files||[]).map(f=>f.machine))].length>=2)?'crossed':'repeatability')}
function machineOf(s,S){return S.files.find(f=>f.id===s.fileId)?.machine||'Unknown'}
function boardOf(s){return String(s.pcbId||s.pcbNo||s.fileName||`file-${s.fileId}`)}
function makePrepared(){
 const app=A(),S=app?.getState(),rules=app?.getCurrentRules()||[],measurementMetric=app?.getMeasurementMetric();if(!app||!S?.samples?.length||!rules.length||!measurementMetric)throw new Error('Import data and configure measurement/filter rules first.');
 const idx=selectedRuleIndex();if(idx>=rules.length)throw new Error('Selected optimizer rule no longer exists.');
 const mode=effectiveMode(),target=$('studyMachine')?.value||S.files[0]?.machine||'Unknown',eligible=s=>mode==='crossed'||machineOf(s,S)===target,byPart=new Map();
 for(const s of S.samples){if(!eligible(s))continue;const p=app.getPartId(s);let d=byPart.get(p);if(!d){d={part:p,samples:[],rows:[]};byPart.set(p,d)}const values=rules.map(r=>s.metrics[r.metric]);d.samples.push(values);const mv=s.metrics[measurementMetric];if(Number.isFinite(mv))d.rows.push({part:p,machine:machineOf(s,S),board:boardOf(s),value:mv})}
 return {app,S,rules,measurementMetric,ruleIndex:idx,byPart,mode,target};
}
function partHits(d,rules,idx,direction,t){for(const values of d.samples){const hits=rules.map((r,i)=>i===idx?C.compare(values[i],direction,t,r.b):C.compare(values[i],r.op,r.a,r.b)),join=$('ruleJoin')?.value||'ALL';if(join==='ALL'?hits.every(Boolean):hits.some(Boolean))return true}return false}
function evaluate(prep,rows,selected,preferredParts,t){
 let g,commonParts=selected.length,repeats=0,machines=[...new Set(rows.map(r=>r.machine))].length,boards=[...new Set(rows.map(r=>r.board))].length,balancedRows=rows.length;
 if(prep.mode==='crossed'){const b=prep.app.balanced(rows);commonParts=b.common.length;repeats=b.min;machines=b.machines.length;balancedRows=b.rows.length;g=C.calculateCrossedANOVA(b.rows.map(r=>({part:r.part,machine:r.machine,value:r.value})))}
 else if(prep.mode==='process'){g=C.calculateProcessVariation(rows);commonParts=g.ok?g.commonParts:selected.length;boards=g.ok?g.boards:boards;repeats=1}
 else {g=C.calculateSingleMachineRepeatability(rows);commonParts=g.ok?g.parts:selected.length;repeats=g.ok?g.repeatsMin:0;machines=1}
 const objective=g?.ok?(prep.mode==='process'?g.processCV:g.pctStudyVariation):NaN;
 return {threshold:t,valid:!!g?.ok&&Number.isFinite(objective),recommended:preferredParts===0||commonParts>=preferredParts,selectedParts:selected.length,commonParts,measurements:rows.length,machines,boards,repeats,balancedRows,objective,g};
}
async function scan(prep,from,to,step,direction,preferredParts){
 const lo=Math.min(from,to),hi=Math.max(from,to),count=Math.floor((hi-lo)/step+1+1e-9);if(count>10000)throw new Error(`This scan would test ${count.toLocaleString()} thresholds. Use a larger Step or a smaller range (maximum 10,000 points).`);
 const thresholds=[];for(let i=0;i<count;i++)thresholds.push(+(lo+i*step).toFixed(10));if(thresholds[thresholds.length-1]<hi-step*1e-8)thresholds.push(+hi.toFixed(10));
 const results=[],allParts=[...prep.byPart.values()],refreshEvery=Math.max(1,Math.floor(thresholds.length/100));
 for(let i=0;i<thresholds.length;i++){const t=thresholds[i],selected=[];for(const d of allParts)if(partHits(d,prep.rules,prep.ruleIndex,direction,t)&&d.rows.length)selected.push(d);const rows=selected.flatMap(d=>d.rows),base=evaluate(prep,rows,selected,preferredParts,t);results.push(base);if(i%refreshEvery===0||i===thresholds.length-1){prep.app.progress('Study Optimizer',`Testing threshold ${i+1} / ${thresholds.length}`,12+80*(i+1)/thresholds.length,`${direction} ${fmt(t,4)} · ${prep.mode}`);await nap(0)}}return results;
}
function labels(mode){if(mode==='repeatability')return {name:'Repeatability %Study Variation',short:'Repeatability %',noun:'repeated pins'};if(mode==='process')return {name:'Process CV',short:'Process CV',noun:'common production pins'};return {name:'GR&R %Study Variation',short:'%GRR',noun:'common pins'}}
function render(result){lastResult=result;const out=$('optimizerOutput'),L=labels(result.mode),valid=result.results.filter(x=>x.valid).sort((a,b)=>a.objective-b.objective);const bestLabel=$('optBestGRR')?.previousElementSibling;if(bestLabel)bestLabel.textContent=`Lowest ${L.short}`;
 if(!valid.length){const maxMachines=Math.max(0,...result.results.map(x=>x.machines||0)),maxCommon=Math.max(0,...result.results.map(x=>x.commonParts||0)),maxRepeats=Math.max(0,...result.results.map(x=>x.repeats||0)),maxBoards=Math.max(0,...result.results.map(x=>x.boards||0));let req='';if(result.mode==='repeatability')req=`Same-board Repeatability needs at least 2 pins/parts with 2 repeated measurements each on machine ${esc(result.target)}.`;else if(result.mode==='process')req='Production Process Variation needs at least 2 physical PCB IDs/boards and 2 common pins/parts.';else req='Crossed GR&R needs at least 2 machines, 2 common pins and 2 repeats per Pin × Machine cell.';out.innerHTML=`<div class="opt-warning"><b>No calculable candidate in this range.</b><br>${req}<br><br><b>Best data availability found:</b><br>Machines: ${maxMachines}<br>Boards: ${maxBoards}<br>Common/repeated pins: ${maxCommon}<br>Repeats: ${maxRepeats}</div>`;return}
 const best=valid[0],unit=result.filterMetric?.unit?` ${result.filterMetric.unit}`:'';$('optBestValue').textContent=`${result.direction} ${fmt(best.threshold,4)}${unit}`;$('optBestGRR').textContent=`${fmt(best.objective,2)}%`;$('optBestParts').textContent=best.commonParts.toLocaleString();$('optBestNdc').textContent=best.g?.ndc===Infinity?'∞':(best.g?.ndc??'—');const coverage=result.preferredParts===0?'No preferred minimum was requested.':best.commonParts>=result.preferredParts?`${best.commonParts} ${L.noun} meets your preferred ${result.preferredParts}.`:`Best result uses ${best.commonParts} ${L.noun}, below your preferred ${result.preferredParts}; it is shown anyway.`;const top=valid.slice(0,50);
 out.innerHTML=`<div class="opt-note"><b>Lowest available ${L.name}:</b> ${fmt(best.objective,2)}% at ${result.direction} ${fmt(best.threshold,4)}${unit}.<br><b>Study mode:</b> ${result.mode==='repeatability'?'Same-board Repeatability':result.mode==='process'?'Production Process Variation':'Crossed GR&R'}${result.mode!=='crossed'?` · Machine ${esc(result.target)}`:''}<br><b>Coverage:</b> ${coverage}<br><br><b>Measurement:</b> ${esc(result.measurementMetric.fullLabel)}<br><b>Optimized filter:</b> Rule ${result.ruleIndex+1} · ${esc(result.filterMetric.fullLabel)}</div><div class="opt-table-wrap"><table class="opt-table"><thead><tr><th>Rank</th><th>Threshold</th><th>${L.short}</th><th>Common/repeated pins</th><th>Measurements</th><th>Machines</th><th>Boards</th><th>Repeats</th></tr></thead><tbody>${top.map((r,i)=>`<tr class="${i===0?'best':''}"><td>${i+1}</td><td>${result.direction} ${fmt(r.threshold,4)}${unit}</td><td>${fmt(r.objective,2)}%</td><td>${r.commonParts}</td><td>${r.measurements}</td><td>${r.machines}</td><td>${r.boards}</td><td>${r.repeats}</td></tr>`).join('')}</tbody></table></div><div class="opt-actions"><button id="applyBestThreshold" class="primary">Apply lowest-variation threshold & analyze</button><button id="downloadOptCsv" class="ghost">Export optimizer CSV</button></div>`;
 $('applyBestThreshold').onclick=async()=>{if(result.app.applyRuleThreshold(result.ruleIndex,result.direction,best.threshold)){result.app.toast(`Applied Rule ${result.ruleIndex+1}: ${result.direction} ${best.threshold}`);if(window.XGRRStudy?.analyzeStudy)await window.XGRRStudy.analyzeStudy();else await result.app.analyze()}};$('downloadOptCsv').onclick=()=>downloadCsv(valid,result);
}
function downloadCsv(rows,result){const L=labels(result.mode),cols=['Threshold','Direction','Study_Mode','Objective_Name','Objective_Percent','Common_Parts','Selected_Parts','Measurements','Machines','Boards','Repeats','Filter_Metric','Measurement_Metric'],lines=[cols.join(',')],q=v=>`"${String(v??'').replaceAll('"','""')}"`;for(const r of [...rows].sort((a,b)=>a.threshold-b.threshold))lines.push([r.threshold,result.direction,result.mode,q(L.name),r.objective,r.commonParts,r.selectedParts,r.measurements,r.machines,r.boards,r.repeats,q(result.filterMetric.fullLabel),q(result.measurementMetric.fullLabel)].join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='Study_Optimizer_Threshold_Scan.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function optimize(){const app=A();try{resetOutput();const prep=makePrepared(),from=+$('optFrom').value,to=+$('optTo').value,step=+$('optStep').value,preferredParts=Math.max(0,Math.floor(+$('optMinParts').value||0)),direction=$('optDirection').value;if(![from,to,step].every(Number.isFinite)||step<=0)throw new Error('Check optimizer range and step.');const filterKey=prep.rules[prep.ruleIndex].metric,filterMetric=prep.S.metrics.get(filterKey),measurementMetric=prep.S.metrics.get(prep.measurementMetric);app.progress('Study Optimizer','Preparing data matrix…',5,`${filterMetric?.fullLabel||filterKey} → ${measurementMetric?.fullLabel||prep.measurementMetric}`);await nap(10);const results=await scan(prep,from,to,step,direction,preferredParts);app.progress('Study Optimizer','Ranking all calculable thresholds…',96);await nap(10);const result={...prep,results,from,to,step,direction,preferredParts,filterMetric,measurementMetric};render(result);app.progress('Done','Lowest-variation threshold search ready.',100);await nap(80);app.hideProgress()}catch(e){app?.hideProgress();console.error(e);$('optimizerOutput').innerHTML=`<div class="opt-warning"><b>Optimizer stopped.</b><br>${esc(e.message||e)}</div>`;app?.toast(e.message||'Optimizer failed')}}
function sync(){const app=A(),rules=app?.getCurrentRules?.()||[],opt=$('optRule'),btn=$('optimizeBtn');if(!opt||!btn)return;const old=+opt.value;if(!rules.length){opt.innerHTML='<option>No filter rules</option>';opt.disabled=btn.disabled=true;resetOutput();return}const S=app.getState();opt.innerHTML=rules.map((r,i)=>`<option value="${i}">Rule ${i+1}: ${esc(S.metrics.get(r.metric)?.fullLabel||r.metric)}</option>`).join('');opt.value=Number.isInteger(old)&&old<rules.length?String(old):'0';opt.disabled=btn.disabled=false}
$('optimizeBtn').onclick=optimize;$('optRule').onchange=resetOutput;const mo=new MutationObserver(sync);mo.observe($('rules'),{childList:true,subtree:true});$('fileList')&&new MutationObserver(sync).observe($('fileList'),{childList:true,subtree:true});$('resetBtn').addEventListener('click',()=>setTimeout(()=>{sync();resetOutput()},0));['studyMode','studyMachine','boardInterpretation'].forEach(id=>$(id)?.addEventListener('change',resetOutput));sync();
})();