(() => {
'use strict';
const C=window.XGRRCore,$=id=>document.getElementById(id),A=()=>window.XGRRApp;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const fmt=(v,d=3)=>Number.isFinite(+v)?(+v).toFixed(d):'—';
const nap=(n=0)=>new Promise(r=>setTimeout(r,n));
function machineOf(s,S){return S.files.find(f=>f.id===s.fileId)?.machine||'Unknown'}
function boardOf(s){return String(s.pcbId||s.pcbNo||s.fileName||`file-${s.fileId}`)}
function installControls(){
 const part=$('partMode');if(!part||$('studyMode'))return;
 const panel=part.closest('.panel'),hint=panel?.querySelector('.hint');if(!panel)return;
 const box=document.createElement('div');box.className='study-config';box.innerHTML=`
 <div class="grid two compact">
  <label class="field"><span>Study mode</span><select id="studyMode"><option value="auto">Auto</option><option value="repeatability">Same-board repeatability (1 machine)</option><option value="crossed">Crossed GR&R (2+ machines)</option><option value="process">Production process variation (different boards)</option></select></label>
  <label class="field"><span>Machine used for single-machine study</span><select id="studyMachine"><option value="">Import data first</option></select></label>
 </div>
 <label class="field"><span>PCB ID interpretation</span><select id="boardInterpretation"><option value="same">Same physical board — PCB IDs are repeated inspections</option><option value="different">Different physical boards — PCB IDs are production samples</option></select></label>
 <div id="studyModeInfo" class="hint strong"></div>`;
 if(hint)hint.after(box);else panel.appendChild(box);
 $('studyMode').addEventListener('change',()=>{updateModeInfo();invalidate()});$('boardInterpretation').addEventListener('change',()=>{if($('studyMode').value==='auto')updateModeInfo();invalidate()});$('studyMachine').addEventListener('change',invalidate);
 refreshMachines();updateModeInfo();
 const fl=$('fileList');if(fl)new MutationObserver(()=>refreshMachines()).observe(fl,{childList:true,subtree:true});
}
function invalidate(){const S=A()?.getState?.();if(S)S.analysis=null;$('results')?.classList.add('hidden')}
function refreshMachines(){const app=A(),S=app?.getState?.();if(!$('studyMachine')||!S)return;const ms=[...new Set(S.files.map(f=>f.machine).filter(Boolean))],old=$('studyMachine').value;$('studyMachine').innerHTML=ms.length?ms.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join(''):'<option value="">Import data first</option>';$('studyMachine').value=ms.includes(old)?old:(ms[0]||'');updateModeInfo()}
function effectiveMode(){const mode=$('studyMode')?.value||'auto',S=A()?.getState?.(),machines=[...new Set((S?.files||[]).map(f=>f.machine).filter(Boolean))];if(mode!=='auto')return mode;if($('boardInterpretation')?.value==='different')return 'process';return machines.length>=2?'crossed':'repeatability'}
function updateModeInfo(){const x=$('studyModeInfo');if(!x)return;const mode=effectiveMode();if(mode==='repeatability')x.innerHTML='<b>Same-board Repeatability:</b> PCB IDs may be different in the CSV but are treated as repeated inspections of the same physical board. The same Component + Pin is one measurement location; repeated values show how much one machine moves.';else if(mode==='process')x.innerHTML='<b>Production Process Variation:</b> PCB ID is treated as a physical board/sample. The program compares the same Component + Pin across different boards and separates board-to-board variation from residual pin-by-board variation.';else x.innerHTML='<b>Crossed GR&R:</b> the same Component + Pin is measured repeatedly by two or more machines to estimate Repeatability and Reproducibility.'}
function passes(values,rules,join){const hits=rules.map((r,i)=>C.compare(values[i],r.op,r.a,r.b));return join==='ALL'?hits.every(Boolean):hits.some(Boolean)}
async function analyzeStudy(){
 const app=A(),S=app?.getState?.();if(!S?.samples?.length)return;
 const rules=app.getCurrentRules(),metric=app.getMeasurementMetric(),join=$('ruleJoin').value,mode=effectiveMode(),target=$('studyMachine')?.value||S.files[0]?.machine||'Unknown';
 app.progress(mode==='process'?'Production Process Study':mode==='repeatability'?'Single-Machine Repeatability':'Crossed GR&R','Selecting pins and measurements…',8);await nap(10);
 const eligible=s=>mode==='crossed'||machineOf(s,S)===target;
 const groups=new Map();for(const s of S.samples){if(!eligible(s))continue;const p=app.getPartId(s);if(!groups.has(p))groups.set(p,[]);groups.get(p).push(s)}
 const selectedByFilter=new Set(),trig=new Map();for(const [p,arr] of groups){let n=0;for(const s of arr){const vals=rules.map(r=>s.metrics[r.metric]);if(passes(vals,rules,join))n++}if(n){selectedByFilter.add(p);trig.set(p,n)}}
 app.progress('Collecting measurements',`${selectedByFilter.size.toLocaleString()} unique pins/parts passed filters`,35);await nap(10);
 const rows=[],trial=new Map();for(const s of S.samples){if(!eligible(s))continue;const p=app.getPartId(s),v=s.metrics[metric];if(!selectedByFilter.has(p)||!Number.isFinite(v))continue;const mach=machineOf(s,S),key=mach+'\0'+p,n=(trial.get(key)||0)+1;trial.set(key,n);const fv=rules.map(r=>s.metrics[r.metric]);rows.push({part:p,machine:mach,board:boardOf(s),value:v,trial:n,pcbNo:s.pcbNo,pcbId:s.pcbId,repetition:s.repetition,component:s.component,pin:s.pin==='__COMP__'?'':s.pin,fileName:s.fileName,volumePath:s.volumePath,filterValues:fv,triggerThisRun:passes(fv,rules,join)})}
 const selected=[...new Set(rows.map(r=>r.part))],byPart=new Map();for(const r of rows){if(!byPart.has(r.part))byPart.set(r.part,[]);byPart.get(r.part).push(r)}
 const summary=selected.map(p=>{const a=byPart.get(p)||[],z=C.summarize(a.map(r=>r.value)),fv=a.flatMap(r=>r.filterValues).filter(Number.isFinite);return {part:p,...z,filterMin:fv.length?Math.min(...fv):NaN,filterMax:fv.length?Math.max(...fv):NaN,triggerCount:trig.get(p)||0}}).sort((a,b)=>b.range-a.range);
 app.progress('Calculating study','Estimating variation components…',72);await nap(10);
 let result,b=null;if(mode==='crossed'){b=app.balanced(rows);result=C.calculateCrossedANOVA(b.rows.map(r=>({part:r.part,machine:r.machine,value:r.value})))}else if(mode==='process')result=C.calculateProcessVariation(rows);else result=C.calculateSingleMachineRepeatability(rows);
 const machines=[...new Set(rows.map(r=>r.machine))],boards=[...new Set(rows.map(r=>r.board))];
 S.analysis={rules,join,metric,selected,selectedByFilter:[...selectedByFilter],rows,summary,grr:result,studyMode:mode,studyMachine:target,boardInterpretation:$('boardInterpretation')?.value||'same',quality:{machines,boards,commonParts:b?.common?.length??result.commonParts??result.parts??0,cells:b?.cells??0,expectedCells:b?.expected??0,minRepeats:b?.min??result.repeatsMin??0,balancedRows:b?.rows?.length??result.observations??rows.length,filteredParts:selectedByFilter.size,partsWithMeasurement:selected.length}};
 app.progress('Rendering results','Preparing study summary…',94);renderStudy();await nap(20);app.progress('Done','Study ready.',100);await nap(80);app.hideProgress();
}
function line(k,v){return `<div class="metric-row"><span>${k}</span><b>${v}</b></div>`}
function qline(k,v){return `<div class="quality-item"><span>${k}</span><b>${esc(v)}</b></div>`}
function renderStudy(){const S=A().getState(),a=S.analysis,r=a.grr,mode=a.studyMode;$('results').classList.remove('hidden');$('statParts').textContent=(a.selectedByFilter?.length||0).toLocaleString();$('statMeasurements').textContent=a.rows.length.toLocaleString();$('statMachines').textContent=a.quality.machines.length;
 if(mode==='repeatability'){$('statGRR').textContent=r.ok?fmt(r.pctStudyVariation,2)+'%':'N/A';$('grrStatus').textContent='single-machine repeatability';$('grrPanel').innerHTML=r.ok?`<div class="status-card ${r.pctStudyVariation<10?'good':r.pctStudyVariation<=30?'warn':'bad'}"><b>Same-board repeatability</b><br>Repeatability %Study Variation = ${fmt(r.pctStudyVariation,2)}%</div>${line('Repeatability SD',fmt(r.repeatabilitySD,6))}${line('6σ repeatability',fmt(r.studyVariation.repeatability,6))}${line('Mean pin range',fmt(r.meanRange,6))}${line('Maximum pin range',fmt(r.maxRange,6))}${line('%Contribution repeatability',fmt(r.pctContribution,2)+'%')}${line('Pins/parts with repeats',r.parts)}${line('Repeats per pin',`${r.repeatsMin}–${r.repeatsMax}`)}${line('ndc',r.ndc===Infinity?'∞':r.ndc)}<div class="hint">PCB IDs are treated as repeated inspections, not different physical boards.</div>`:`<div class="status-card warn"><b>Repeatability not calculated</b><br>${esc(r.reason)}</div>`;$('qualityPanel').innerHTML=`<div class="quality-list">${qline('Study mode','Same-board repeatability')}${qline('Machine',a.studyMachine)}${qline('Unique pins passing filter',a.quality.filteredParts)}${qline('Pins with measurement data',a.quality.partsWithMeasurement)}${qline('PCB IDs seen',a.quality.boards.length)}${qline('Interpretation','PCB IDs = repeated inspections of same board')}</div>`}
 else if(mode==='process'){$('statGRR').textContent=r.ok?fmt(r.processCV,2)+'%':'N/A';$('grrStatus').textContent='process CV';$('grrPanel').innerHTML=r.ok?`<div class="status-card"><b>Production process variation</b><br>Process CV = ${fmt(r.processCV,2)}%</div>${line('Process SD',fmt(r.sd.process,6))}${line('6σ process variation',fmt(r.studyVariation.process,6))}${line('Board-to-board SD',fmt(r.sd.boardToBoard,6))}${line('Pin × board residual SD',fmt(r.sd.residual,6))}${line('%Study Variation process',fmt(r.pctStudyVariation,2)+'%')}${line('%Contribution process',fmt(r.pctContribution,2)+'%')}${line('Physical boards',r.boards)}${line('Common pins/parts',r.commonParts)}<div class="hint">PCB ID is treated as a different physical production board. This is a process consistency study, not GR&R.</div>`:`<div class="status-card warn"><b>Process variation not calculated</b><br>${esc(r.reason)}</div>`;$('qualityPanel').innerHTML=`<div class="quality-list">${qline('Study mode','Production process variation')}${qline('Machine',a.studyMachine)}${qline('Physical boards / PCB IDs',a.quality.boards.length)}${qline('Unique pins passing filter',a.quality.filteredParts)}${qline('Pins with measurement data',a.quality.partsWithMeasurement)}${qline('Interpretation','PCB IDs = different physical boards')}</div>`}
 else {$('statGRR').textContent=r.ok?fmt(r.pctStudyVariation,2)+'%':'N/A';$('grrStatus').textContent='crossed GR&R';$('grrPanel').innerHTML=r.ok?`<div class="status-card ${r.pctStudyVariation<10?'good':r.pctStudyVariation<=30?'warn':'bad'}"><b>Crossed GR&R</b><br>%Study Variation GR&R = ${fmt(r.pctStudyVariation,2)}%</div>${line('Repeatability variance',fmt(r.variance.repeatability,6))}${line('Reproducibility variance',fmt(r.variance.reproducibility,6))}${line('Machine × Part interaction',fmt(r.variance.interaction,6))}${line('Part-to-Part variance',fmt(r.variance.partToPart,6))}${line('%Contribution GR&R',fmt(r.pctContribution,2)+'%')}${line('ndc',r.ndc===Infinity?'∞':r.ndc)}`:`<div class="status-card warn"><b>Crossed GR&R not calculated</b><br>${esc(r.reason)}</div>`;$('qualityPanel').innerHTML=`<div class="quality-list">${qline('Study mode','Crossed GR&R')}${qline('Machines',a.quality.machines.join(', '))}${qline('Unique pins passing filter',a.quality.filteredParts)}${qline('Common pins on every machine',a.quality.commonParts)}${qline('Minimum repeats per cell',a.quality.minRepeats)}</div>`}
 renderTable();setTimeout(()=>window.XGRRUI?.updateAnalysisSummary?.(),0)}
function renderTable(){const a=A().getState().analysis,q=($('tableSearch')?.value||'').trim().toLowerCase();$('pinTable').innerHTML=a.summary.filter(r=>!q||r.part.toLowerCase().includes(q)).slice(0,1500).map(r=>`<tr><td>${esc(r.part)}</td><td>${r.n}</td><td>${fmt(r.mean)}</td><td>${fmt(r.min)}</td><td>${fmt(r.max)}</td><td>${fmt(r.range)}</td><td>${fmt(r.sd)}</td><td>${fmt(r.cv,2)}</td><td>${fmt(r.filterMin)}</td><td>${fmt(r.filterMax)}</td></tr>`).join('')}
function ws(rows){const s=XLSX.utils.json_to_sheet(rows);if(s['!ref'])s['!autofilter']={ref:s['!ref']};return s}
async function exportStudy(){const app=A(),S=app.getState(),a=S.analysis;if(!a||!window.XLSX)return;const mode=a.studyMode;if(mode==='crossed')return;app.progress('Creating Excel workbook','Preparing study sheets…',10);await nap(10);const wb=XLSX.utils.book_new(),mi=S.metrics.get(a.metric),method=mode==='repeatability'?'Same-board single-machine repeatability':'Production process variation';const data=a.rows.map(r=>({Part:r.part,Machine:r.machine,Physical_Board:mode==='process'?r.board:'SAME_BOARD',Trial:r.trial,Measurement:r.value,PCB_ID:r.pcbId,PCB_No:r.pcbNo,Component:r.component,Pin:r.pin,Source_File:r.fileName}));XLSX.utils.book_append_sheet(wb,ws(data),'Study_Data');XLSX.utils.book_append_sheet(wb,ws(a.summary.map(r=>({Part:r.part,N:r.n,Mean:r.mean,Min:r.min,Max:r.max,Range:r.range,SD:r.sd,CV_Percent:r.cv,Filter_Min:r.filterMin,Filter_Max:r.filterMax}))),'Part_Stability');const r=a.grr,summary=[{Metric:'Study mode',Value:method},{Metric:'Measurement',Value:mi?.fullLabel||a.metric},{Metric:'Unique parts/pins',Value:a.selected.length},{Metric:'Observations',Value:a.rows.length}];if(r.ok&&mode==='repeatability')summary.push({Metric:'Repeatability SD',Value:r.repeatabilitySD},{Metric:'6 sigma repeatability',Value:r.studyVariation.repeatability},{Metric:'Repeatability %Study Variation',Value:r.pctStudyVariation},{Metric:'%Contribution repeatability',Value:r.pctContribution},{Metric:'Mean range',Value:r.meanRange},{Metric:'Max range',Value:r.maxRange},{Metric:'ndc',Value:r.ndc});if(r.ok&&mode==='process')summary.push({Metric:'Physical boards',Value:r.boards},{Metric:'Process SD',Value:r.sd.process},{Metric:'Board-to-board SD',Value:r.sd.boardToBoard},{Metric:'Residual SD',Value:r.sd.residual},{Metric:'6 sigma process',Value:r.studyVariation.process},{Metric:'Process CV %',Value:r.processCV},{Metric:'Process %Study Variation',Value:r.pctStudyVariation});if(!r.ok)summary.push({Metric:'Status',Value:r.reason});XLSX.utils.book_append_sheet(wb,ws(summary),'Study_Summary');XLSX.utils.book_append_sheet(wb,ws([{Setting:'Study mode',Value:method},{Setting:'PCB ID interpretation',Value:a.boardInterpretation},{Setting:'Machine',Value:a.studyMachine},{Setting:'Part identity',Value:$('partMode').value},{Setting:'Selection behavior',Value:'If filter matches at least once, retain all available measurement repeats for that Component + Pin'}]),'Settings');app.progress('Creating Excel workbook','Writing file…',85);await nap(20);const stamp=new Date().toISOString().slice(0,19).replace(/[:T]/g,'-');XLSX.writeFile(wb,`XRay_${mode==='repeatability'?'Repeatability':'Process'}_${stamp}.xlsx`,{compression:true});app.progress('Excel exported','Download started.',100);await nap(120);app.hideProgress()}
function init(){installControls();const btn=$('analyzeBtn');btn?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();analyzeStudy().catch(err=>{A()?.hideProgress?.();console.error(err);A()?.toast?.(err.message||'Study failed')})},true);$('tableSearch')?.addEventListener('input',()=>{if(A()?.getState?.().analysis?.studyMode)renderTable()});$('exportBtn')?.addEventListener('click',e=>{const mode=A()?.getState?.().analysis?.studyMode;if(mode&&mode!=='crossed'){e.preventDefault();e.stopImmediatePropagation();exportStudy().catch(err=>{A()?.hideProgress?.();console.error(err);A()?.toast?.(err.message||'Export failed')})}},true)}
window.XGRRStudy={effectiveMode,analyzeStudy,refreshMachines};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();